export type Technology = { id: string; name: string; sector: string; icon: string; description: string; keywords: string[]; applications: string[]; url: string; source: string; stage: string }
export const technologies: Technology[] = [
  { id: 'storage', name: 'Long-duration energy storage', sector: 'Storage', icon: '▥', description: 'Store renewable electricity for hours, days, or longer. Explore the materials and systems that keep clean power available when it is needed.', keywords: ['battery', 'batteries', 'storage', 'flow battery', 'iron air', 'lithium', 'sodium'], applications: ['Grid balancing', 'Renewable firming', 'Industrial backup'], url: 'https://www.energy.gov/energy-storage', source: 'U.S. Department of Energy', stage: 'Scaling up' },
  { id: 'solar', name: 'Next-generation solar', sector: 'Solar', icon: '☼', description: 'From tandem cells to smarter photovoltaic systems, discover approaches to turning more sunlight into useful electricity.', keywords: ['solar', 'photovoltaic', 'perovskite', 'tandem', 'silicon'], applications: ['Rooftop generation', 'Utility-scale power', 'Building-integrated solar'], url: 'https://www.energy.gov/eere/solar/solar-energy-technologies-office', source: 'U.S. Department of Energy', stage: 'Evolving' },
  { id: 'hydrogen', name: 'Clean hydrogen', sector: 'Hydrogen', icon: 'H₂', description: 'Electrolysis, new catalysts, and better infrastructure open pathways to decarbonize hard-to-electrify processes.', keywords: ['hydrogen', 'electrolysis', 'electrolyzer', 'fuel cell', 'catalyst'], applications: ['Low-carbon steel', 'Chemical feedstocks', 'Long-duration storage'], url: 'https://www.energy.gov/eere/fuelcells/hydrogen-and-fuel-cell-technologies-office', source: 'U.S. Department of Energy', stage: 'Emerging' },
  { id: 'grid', name: 'An intelligent, flexible grid', sector: 'Grid', icon: '⌁', description: 'Connected devices, advanced inverters, and flexible demand help electricity networks integrate variable renewable energy.', keywords: ['grid', 'inverter', 'demand response', 'microgrid', 'transmission', 'virtual power'], applications: ['Virtual power plants', 'Community microgrids', 'Peak demand reduction'], url: 'https://www.energy.gov/oe/grid-modernization', source: 'U.S. Department of Energy', stage: 'Scaling up' },
  { id: 'wind', name: 'Advanced wind systems', sector: 'Wind', icon: '✣', description: 'Larger turbines, floating platforms, and smarter operations expand where wind energy can be harvested.', keywords: ['wind', 'turbine', 'offshore', 'floating', 'aerodynamic'], applications: ['Offshore generation', 'Remote community power', 'Hybrid renewable plants'], url: 'https://www.energy.gov/eere/wind/wind-energy-technologies-office', source: 'U.S. Department of Energy', stage: 'Evolving' },
  { id: 'geothermal', name: 'Next-generation geothermal', sector: 'Geothermal', icon: '≋', description: 'Enhanced reservoirs and closed-loop systems explore ways to deliver around-the-clock energy from heat beneath our feet.', keywords: ['geothermal', 'thermal', 'heat pump', 'reservoir', 'drilling'], applications: ['Clean firm electricity', 'District heating', 'Industrial process heat'], url: 'https://www.energy.gov/eere/geothermal/geothermal-technologies-office', source: 'U.S. Department of Energy', stage: 'Emerging' },
]
export const sectors = ['All energy', ...technologies.map(t => t.sector)]
